### ISSUE TITLE
error response

### ISSUE THREAD

**Issue by GesSaaS** [hotelbeds-sdk/hotel-api-sdk-java#16]
BookingRS bookingRS =
                                apiClient.confirm(Booking.builder().withHolder("Rosetta", "Pruebas").clientReference("SDK Test")
                                    .remark("***SDK***TESTING").addRoom(rateKey, confirmRoom).build());

Exception in thread "main" HotelApiSDKException(error=HotelbedsError(code=Invalid response, message=Wrong content typeapplication/xml;charset=UTF-8))
    at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:702)
    at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:658)
    at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.doBookingConfirm(HotelApiClient.java:350)

**Comment by Verdoso** [comment]
Hi,

This is most probably an authentication or quota error, as the service controlling those aspects is the one that answers with non-json pages. We have to improve the error handling on that side.

In the mean time, if you enable the com.hotelbeds.distribution.hotel_api_sdk.helpers.LoggingRequestInterceptor log level and set it to DEBUG or TRACE, you will be able to see in your logs the full traffic going to the server and the response, and that should help you detect the issue.
For example, using Log4j, one would add something like that to the log4j.xml config file:
'''
  <logger name="com.hotelbeds.distribution.hotel_api_sdk.helpers.LoggingRequestInterceptor">
    <level value="debug" />
  </logger>
'''
Let us knows how it goes,
Cheers,
D.
