### ISSUE TITLE
400 Bad request on production

### ISSUE THREAD

**Issue by echozbb** [hotelbeds-sdk/hotel-api-sdk-java#28]
Got bad request in production booking. Would you advise the reason?

2017-05-13 19:56:23.065 [http-nio-8080-exec-6]
INFO  c.c.h.s.HotelBedsBookingService - booking request : {
  "holder" : {
    "name" : "XUERU",
    "surname" : "ZHANG"
  },
  "rooms" : [ {
    "rateKey" : "20170810|20170811|W|283|137091|STU.SU|BAR-ALL|RO||3~2~0||N@56239139EE3049D992A987D5971F057A",
    "paxes" : [ {
      "roomId" : 1,
      "type" : "AD",
      "age" : 30,
      "name" : "XUERU",
      "surname" : "ZHANG"
    }, {
      "roomId" : 1,
      "type" : "AD",
      "age" : 30,
      "name" : " ZICHAO ",
      "surname" : "ZENG"
    }, {
      "roomId" : 2,
      "type" : "AD",
      "age" : 30,
      "name" : "SHANGFENG",
      "surname" : " ZENG"
    }, {
      "roomId" : 2,
      "type" : "AD",
      "age" : 30,
      "name" : "ZIYUE",
      "surname" : "ZHANG"
    }, {
      "roomId" : 3,
      "type" : "AD",
      "age" : 30,
      "name" : "RIHONG",
      "surname" : "CHEN"
    }, {
      "roomId" : 3,
      "type" : "AD",
      "age" : 30,
      "name" : "GUOYAN",
      "surname" : "ZHANG  "
    } ]
  } ],
  "clientReference" : "20284"
} 
2017-05-13 19:56:23.066 [http-nio-8080-exec-6]
INFO  c.h.d.h.h.LoggingRequestInterceptor - Request: HTTP/1.1 POST https://api.hotelbeds.com/hotel-api/1.0/bookings, body:608 bytes 
2017-05-13 19:56:23.066 [http-nio-8080-exec-6]
DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: Content-Type: "application/json; charset=utf-8" 
2017-05-13 19:56:23.066 [http-nio-8080-exec-6]
DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: Content-Length: "608" 
2017-05-13 19:56:23.066 [http-nio-8080-exec-6]
DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: Accept: "application/json" 
2017-05-13 19:56:23.066 [http-nio-8080-exec-6]
DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: Api-Key: "cb3fc6qz8cn9q4jgxsp2w8wp" 
2017-05-13 19:56:23.066 [http-nio-8080-exec-6]
DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: User-Agent: "hotel-api-sdk-java, 0.12-SNAPSHOT" 
2017-05-13 19:56:23.066 [http-nio-8080-exec-6]
DEBUG c.h.d.h.h.LoggingRequestInterceptor -   Header: X-Signature: "0150b13ea106d1358ec09159b40e47b0e66efc09d44b6572238e68bcb69a9c6f" 
2017-05-13 19:56:23.862 [http-nio-8080-exec-6]
INFO  c.h.d.h.h.LoggingRequestInterceptor - Response: 400  
2017-05-13 19:56:23.862 [http-nio-8080-exec-6]
...
ERROR c.c.h.s.HotelBedsBookingService - Error while booking the hotel :  
com.hotelbeds.distribution.hotel_api_sdk.types.HotelApiSDKException: HotelSDKException (Error INVALID_DATA-9631493e-0233-4c23-a831-9ae13a1e61a8 while performing operation
at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:877) ~[hotel-api-sdk-0.12-20170307.134822-3.jar:0.12-SNAPSHOT]
at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:816) ~[hotel-api-sdk-0.12-20170307.134822-3.jar:0.12-SNAPSHOT]
at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.doBookingConfirm(HotelApiClient.java:467) ~[hotel-api-sdk-0.12-20170307.134822-3.jar:0.12-SNAPSHOT

**Comment by vmavromatis** [comment]
Hi @echozbb, apologies for the late response. When making a booking with no credit card details, please use our version 1.2 endpoint (not 1.0) [as per the documentation](https://developer.hotelbeds.com/docs/read/apitude_booking/Booking_Confirmation).

In the future, please use this space only to refer to SDK issues. For all API issues please refer to apitude@hotelbeds.com.
