### ISSUE TITLE
Error getting hotels from ContentAPI

### ISSUE THREAD

**Issue by vmavromatis** [hotelbeds-sdk/hotel-api-sdk-java#32]
```java
import com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient;
import com.hotelbeds.distribution.hotel_api_sdk.types.HotelApiSDKException;
import com.hotelbeds.hotelcontentapi.auto.messages.Category;
import com.hotelbeds.hotelcontentapi.auto.messages.Content;
import com.hotelbeds.hotelcontentapi.auto.messages.Country;
import com.hotelbeds.hotelcontentapi.auto.messages.Destination;
import com.hotelbeds.hotelcontentapi.auto.messages.Facility;
import com.hotelbeds.hotelcontentapi.auto.messages.GeoLocation;
import com.hotelbeds.hotelcontentapi.auto.messages.Hotel;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelFacility;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelPhone;
import com.hotelbeds.hotelcontentapi.auto.messages.HotelPointOfInterest;
import com.hotelbeds.hotelcontentapi.auto.messages.Image;

@Override
 public boolean importHotels(Date lastUpdateStarted, Date lastUpdateCompleted, boolean lightUpdate) {

  Map<String, ProviderCity> providerCities = providerCityDAO.findEnabledByProvider(getProvider()).stream().collect(Collectors.toMap(ProviderCity::getProviderId, Function.identity()));
  Map<Integer, ProviderHotelFeature> providerFeatures = new HashMap<>();
  Map<Integer, ProviderDistanceType> providerDistances = new HashMap<>();
  Stream<Facility> facilitiesResp = null;
  Stream<Hotel> hotelsResp = null;

  try (HotelApiClient apiClient = new HotelApiClient(HotelbedsApitudeConstants.APIKEY, HotelbedsApitudeConstants.SECRET)) {

   apiClient.setReadTimeout(HotelbedsApitudeConstants.READ_TIMEOUT);
   apiClient.setDefaultLanguage(HotelbedsApitudeConstants.LANGUAGE_DEFAULT);
   apiClient.init();

   facilitiesResp = apiClient.facilitiesStream(HotelbedsApitudeConstants.LANGUAGE_DEFAULT, false);
   hotelsResp = apiClient.hotelsStream();

   apiClient.close();
  }
  catch (HotelApiSDKException e) {
   logger.error(e.getError().getCode() + " - " + e.getError().getMessage());
  }

  if (hotelsResp == null || facilitiesResp == null) {
   logger.error("Hotels or Facilieties response is empty!");
   return false;
  }

  processFacilities(facilitiesResp, providerFeatures);
  processHotels(hotelsResp, providerCities, providerFeatures, providerDistances);

  return true;
 }
```
```
2017-12-06 12:26:55 INFO  [LoggingRequestInterceptor] Request: HTTP/1.1 GET https://api.test.hotelbeds.com/hotel-content-api/1.0/hotels?countryCode=&destinationCode=&codes=&from=1&to=1000&fields=all&language=ENG
2017-12-06 12:27:05 INFO  [LoggingRequestInterceptor] Response: 200 OK
2017-12-06 12:27:05 INFO  [LoggingRequestInterceptor]   Request took 10093 ms
2017-12-06 12:27:25 ERROR [HotelApiClient] Error parsing JSON response: 
com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class java.time.LocalTime] from String value; no single-String constructor/factory method (through reference chain: com.hotelbeds.hotelcontentapi.auto.messages.HotelsRS["hotels"]->com.hotelbeds.hotelcontentapi.auto.messages.Hotel["facilities"]->com.hotelbeds.hotelcontentapi.auto.messages.HotelFacility["timeFrom"])

**Comment by Verdoso** [comment]
Hi there,
The error 

> JsonMappingException: Can not instantiate value of type [simple type, class java.time.LocalTime] from String.

usually means you are missing the jackson-datatype-jsr310 dependency. The classes in the package java.time are new in Java 8 so Jackson does not know how to treat them, as it has to be remain compatible, unless you add that explicit dependency.
If you check the SDK, you can see the hotel-api-model module has that library as a dependency ([pom.xml](https://github.com/hotelbeds-sdk/hotel-api-sdk-java/blob/master/hotel-api-model/pom.xml))
```
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-jsr310</artifactId>
      <version>2.6.3</version>
    </dependency>
```
Adding that dependency should have you good to go.
Good luck!

**Comment by vmavromatis** [comment]
Hi @Verdoso,

Glad to see you are keeping an eye on this!

Yes I have jsr310 in my pom.xml I opened this ticket for a client, but this may be of use to him.

I'm having some trouble reproducing because I keep getting this:
```
20171207 11:19:27 ERROR-  - ContentElementSpliterator - Error retrieving list of elements
HotelApiSDKException(error=HotelbedsError(code=Invalid response, message=Wrong content typetext/xml))
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteContentAPI(HotelApiClient.java:952)
	at com.hotelbeds.distribution.hotel_api_sdk.ContentElementSpliterator.getElementBlock(ContentElementSpliterator.java:88)
	at com.hotelbeds.distribution.hotel_api_sdk.ContentElementSpliterator.<init>(ContentElementSpliterator.java:72)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.getAllElements(HotelApiClient.java:765)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.getAllFacilityTypes(HotelApiClient.java:679)
	at com.hotelbeds.demo.simple.ContentFacilityTypologies.main(ContentFacilityTypologies.java:45)
```

on code that used to work fine. This is the code that used to work.
```java
import com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient;
import com.hotelbeds.distribution.hotel_api_sdk.types.HotelApiSDKException;
import com.hotelbeds.hotelcontentapi.auto.messages.*;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class ContentFacilityTypologies {

    public static void main(String[] args) {
        // Perform the request and browse the results
        try (final HotelApiClient apiClient = new HotelApiClient("xxxxxxx", "xxxxxxx" )) {
            apiClient.setReadTimeout(20000);
            apiClient.init();

            for (FacilityType element : apiClient.getAllFacilityTypes("ENG", false)) {
                System.out.println(element);
            }

        } catch (HotelApiSDKException e) {
            log.error("Error requesting content", e);

        }
    }

}
```

**Comment by Verdoso** [comment]
Hi @vmavromatis,
The "code=Invalid response, message=Wrong content typetext/xml)" seems to tell us that there is something wrong with the response, as it is not proper XML. The Hotelbeds backend should return XML even in case of error, so that usually means there is some communication error and the usual suspect in this case is the Authentication Gateway, as when you have an overquota error, an expired ApiKey or something like that, the answer it sends back is not XML but plain HTML and that makes the SDK barf.

That's one of the things I did not have time improving 😄 

The next step would be to enable full logging for the communication and you will be able to see the response that is being returned and proceed from there. To see all the traffic between the client and the backend set the log level of the class com.hotelbeds.distribution.hotel_api_sdk.helpers.LoggingRequestInterceptor to TRACE and you'll get the response in logs.

Cheers!
PD: I would recommend opening a different issue for this other problem as it would make finding a solution for this easier in the future 😉

**Comment by vmavromatis** [comment]
Good advice @Verdoso! Much appreciated ;)
