### ISSUE TITLE
Support Of TAX break up

### ISSUE THREAD

**Issue by sharma-hitesh** [hotelbeds-sdk/hotel-api-sdk-java#37]
Hi
We recently got enabled the TAX information in our account.
  
Looks like the Tax information structure is not supported by the SDK version that we are using (hotel-api-model-0.13-20170421.083421-1 and hotel-api-sdk-0.13-20170421.083543-1)

Now when we are trying to make the availability requests, on the account where we got the TAX information enabled, we are getting the following exception:
 
Please help in getting the SDK version that is compatible with the TAX information.

SEVERE: Error parsing JSON response: 

com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of com.hotelbeds.hotelapimodel.auto.common.SimpleTypes$TaxType from String value 'TAXESANDFEES': value not one of declared Enum instance names: [TAX, FEE]

 at [Source: java.io.StringReader@27589d14; line: 1, column: 1221] (through reference chain: com.hotelbeds.hotelapimodel.auto.messages.AvailabilityRS["hotels"]->com.hotelbeds.hotelapimodel.auto.model.Hotels["hotels"]->java.util.ArrayList[0]->com.hotelbeds.hotelapimodel.auto.model.Hotel["rooms"]->java.util.ArrayList[0]->com.hotelbeds.hotelapimodel.auto.model.Room["rates"]->java.util.ArrayList[0]->com.hotelbeds.hotelapimodel.auto.model.Rate["taxes"]->com.hotelbeds.hotelapimodel.auto.model.Taxes["taxes"]->java.util.ArrayList[0]->com.hotelbeds.hotelapimodel.auto.model.Tax["type"])
at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
.
.
.
at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.transformToGenericResponse( HotelApiClient.java:891)
at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:862)
at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:803)
at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.doAvailability(HotelApiClient.java:365)
at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.availability(HotelApiClient.java:359)

**Comment by vmavromatis** [comment]
Hi @sharma-hitesh as of now this should be implemented. Can you please try the latest SDK release with:

```
<dependency>
      <groupId>com.hotelbeds.hotel-api-sdk-java</groupId>
      <artifactId>hotel-api-sdk</artifactId>
      <version>0.14-SNAPSHOT</version>
</dependency>
```

and let me know if it works for you?

Regards

**Comment by sharma-hitesh** [comment]
Yes, it works now

**Comment by vmavromatis** [comment]
Good to hear! Closing
