### ISSUE TITLE
0.14-SNAPSHOT can't do availability

### ISSUE THREAD

**Issue by prettyvoid** [hotelbeds-sdk/hotel-api-sdk-java#39]
> com.fasterxml.jackson.databind.JsonMappingException: java.lang.String cannot be cast to java.time.LocalDate (through reference chain: com.hotelbeds.hotelapimodel.auto.messages.AvailabilityRQ["stay"]->com.hotelbeds.hotelapimodel.auto.model.Stay["checkIn"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3893)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3207)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.transformToRequestBody(HotelApiClient.java:1217)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.generateRequestBuilder(HotelApiClient.java:955)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:996)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:911)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.doAvailability(HotelApiClient.java:354)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.availability(HotelApiClient.java:342)

**Comment by Verdoso** [comment]
That's usually a sign that you are missing the JSR-310 Jackson adapters so your JsonSerializacion does not know how to transform a String into a LocalDate.
The library has moved to a new home https://github.com/FasterXML/jackson-modules-java8 but if you are using an older version of Jackson you can still use the old versions https://mvnrepository.com/artifact/com.fasterxml.jackson.datatype/jackson-datatype-jsr310

Cheers!

**Comment by prettyvoid** [comment]
@Verdoso This problem only happens to me in 0.14, when I switch to 0.13 everything works fine. I checked my effective pom when I have 0.13 and 0.14 and both of them have jsr310 included, version 2.9.5.

Any ideas? Thank you

**Comment by Verdoso** [comment]
I just cloned 0-14-SNAPSHOT and performed an availability request simply with the hotelapi-sdk-demo... 

> 20180611 21:17:35 INFO -  - RequestingAvailability - Requesting availability...
20180611 21:17:37 INFO -  - RequestingAvailability - There are 41 hotels
20180611 21:17:37 INFO -  - RequestingAvailability - -----------------------------------------
20180611 21:17:37 INFO -  - RequestingAvailability - Hotel (LON-88918) - Croydon Park Hotel (4 STARS; from 454.44GBP)
20180611 21:17:37 INFO -  - RequestingAvailability - Double or Twin STANDARD - BED AND BREAKFAST 454.44GBP
20180611 21:17:37 INFO -  - RequestingAvailability - Double or Twin STANDARD - HALF BOARD 607.17GBP
20180611 21:17:37 INFO -  - RequestingAvailability - -----------------------------------------
20180611 21:17:37 INFO -  - RequestingAvailability - Hotel (LON-109171) - King Solomon (2 STARS; from 251.22GBP)
20180611 21:17:37 INFO -  - RequestingAvailability - TRIPLE STANDARD - CONTINENTAL BREAKFAST 267.00GBP
20180611 21:17:37 INFO -  - RequestingAvailability - FAMILY ROOM STANDARD - CONTINENTAL BREAKFAST 297.00GBP

Compare with that project and see if you have the same base jackson libraries, it might be some other library you have has included an incompatible version of the base jackson library, for example.
Good luck!

**Comment by vmavromatis** [comment]
Thank you @Verdoso!
@prettyvoid I am also unable to produce this issue with 0-14-SNAPSHOT. Just to make sure, is `jackson-datatype-jsr310` inside the pom of **hotel-api-model**? It's also not an older version (2.6.3) and it works fine.

**Comment by prettyvoid** [comment]
JSR310 was always there but I managed to fix it and I seriously have no idea what exactly happened in my case. I had to go to my local maven folders `\.m2\repository\com\hotelbeds\hotel-api-sdk-java` and delete 0.14 then it got re-imported by maven and all is good now, no more errors.

Thanks a lot

**Comment by prettyvoid** [comment]
I've tried 0.14 in a clean project and like you guys stated it works fine. 

I was able to pinpoint the culprit in my main project to the following dependency
```
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-jaxb-annotations</artifactId>
            <version>${jackson.version}</version>
        </dependency>
```
jackson.version is 2.9.5

As soon as I remove this dependency from my pom the error I mentioned above vanishes. I'm not sure why 0.14 clashes with this dependency but 0.13 does not.

Any ideas?

**Comment by prettyvoid** [comment]
@Verdoso @vmavromatis Any updates on this? I think it's due to the newly added annotations in the AvailabilityRS class but I'm not sure how to resolve.

**Comment by Verdoso** [comment]
The SDK has jackson 2.6.3 as dependency, if you instead include 2.9.5, you'll have those issues. As I said in my first message, jackson-datatype-jsr310 has been deprecated and is now jackson-datatype-jdk8. This change was made in version 2.8.5 so that seems to explain what is happening to you. One thing you might want to try is to include jackson-datatype-jdk8 and exclude jackson-datatype-jsr310 in your project, and see if that makes it work. It might.
Otherwise, if code compiled agaisnt 2.6.3 is unable to run with 2.9.5 jackson versions, you'll be be stuck with version 2.6.3 unless you get your own sdk version compiled with 2.9.5, or the SDK is upgraded. The latter might break other people's code, so it's something to be considered carefully.
Cheers!
