### ISSUE TITLE
Getting SSL Handshake Exception in Staging Environment

### ISSUE THREAD

**Issue by DhanushkaKumara** [hotelbeds-sdk/hotel-api-sdk-java#59]
Hi Support,

We are getting SSL Handshake error for hotel api with jdk 1.8 in staging environment. 
But this working fine with jdk 1.7
```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
```
**Endpoint: https://api.test.hotelbeds.com/hotel-api/1.0/hotels
API: qh7javyaw8wjfcfeqfj2wf79**

**Comment by DhanushkaKumara** [comment]
APItude support unable to response regarding this and they asked to raised issue here.

**Comment by vmavromatis** [comment]
Hi @DhanushkaKumara the minimum protocol we allow to connect is TLS 1.1 make sure you are using this please. Also import the certificae you used in 1.7 in the Java folder of 1.8. Hope this helps.

**Comment by vmavromatis** [comment]
Please see here for more info in case it helps: https://stackoverflow.com/questions/6353849/received-fatal-alert-handshake-failure-through-sslhandshakeexception

**Comment by vmavromatis** [comment]
@DhanushkaKumara Please specify whether you are using the SDK or not. THank you.

**Comment by DhanushkaKumara** [comment]
Hi @vmavromatis we are using APItude hotel API.
