### ISSUE TITLE
Availability.builder java.time.LocalDate casting exception

### ISSUE THREAD

**Issue by 1hamidreza** [hotelbeds-sdk/hotel-api-sdk-java#60]
Hi, 
I tried to use the Java SDK and tried to run the demo application which has been provided but got the below Exception : 

`20200122 15:06:43 INFO -  - Test - Requesting status...
20200122 15:06:44 INFO -  - Test - Requesting availability...
20200122 15:06:44 INFO -  - Test - Requesting availability from 2020-02-24 to 2020-02-25 for 2 adults and 0 children
HotelApiSDKException(error=HotelbedsError(code=Error parsing JSON response, message=java.lang.String cannot be cast to java.time.LocalDate (through reference chain: com.hotelbeds.hotelapimodel.auto.messages.AvailabilityRQ["stay"]->com.hotelbeds.hotelapimodel.auto.model.Stay["checkIn"])))
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.transformToRequestBody(HotelApiClient.java:1224)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.generateRequestBuilder(HotelApiClient.java:955)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:996)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.callRemoteAPI(HotelApiClient.java:911)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.doAvailability(HotelApiClient.java:354)
	at com.hotelbeds.distribution.hotel_api_sdk.HotelApiClient.availability(HotelApiClient.java:342)`

It seems that Jackson can't serialize LocalDate properly. Can you please advise how can I solve the problem ? 

_Hamid

**Comment by Verdoso** [comment]
The format of the string seems to be correct, 2020-02-24, so please verify that you have the appropriate jackson jars available at runtime (you need jackson-datatype-jsr310-2.6.3 and related, not just jackson core).

Good luck!

**Comment by 1hamidreza** [comment]
Thanks for your reply Verdoso, 
I noticed that I have another dependency in my pom.xml which is using jackson core 2.9.9 and this is causing the issue. 
As the other dependency is forced to use jackson 2.9.x is there anyway that we can manage to use same jackson version for hotel-api-sdk ?

_Hamid

**Comment by Verdoso** [comment]
You might try to add jackson-datatype-jsr310-2.9.9 explicitely and that should override version the SDK 2.6.3 version. Make sure you don't end up having both versions in the classpath at the same time.

If 2.9.9 does not have incompatible changes with 2.6.3 that the SDK is using, that should work. If they are not compatible, that will make things harder as you will need to make changes so they, the SDK and your other dependency, end up using a compatible version.

But try that first and cross your fingers ;)

**Comment by 1hamidreza** [comment]
Ok @Verdoso , 
I got the issue. It seems that we need to register JavaTimeModule in jackson ObjectMapper. It will solve the issue. 
My suggestion is to add 

`
this.mapper.registerModule(new JavaTimeModule());
`

line to HotelApiClient init() method to register the module and it will serialize the LocalDate afterward. It seems that it is required for newer version of JDK and Jackson. 

_Hamid

**Comment by Verdoso** [comment]
Glad you found out what the problem was. Regarding adding it to HotelApiClient, I'll defer to Hotelbeds support for that. I no longer work at Hotelbeds.
